package com.ttvnp.ttj_asset_android_client.domain.model

enum class ErrorCode(val rawValue: Int) {
    NO_ERROR(0),

    // system error
    ERROR_CANNOT_CONNECT_TO_SERVER(1),
    ERROR_LOCKED_OUT(3),

    // service error
    ERROR_ILLEGAL_DATA_STATE_ERROR(101),
    ERROR_UNKNOWN_SERVER_ERROR(102),
    ERROR_DEVICE_NOT_REGISTERED(103),
    ERROR_CANNOT_REGISTER_DEVICE(104),
    ERROR_CANNOT_UPDATE_USER(105),
    ERROR_CANNOT_UPDATE_DEVICE(106),
    ERROR_CANNOT_FIND_TARGET_USER(107),

    // validation error
    ERROR_VALIDATION_EMAIL(1001),
    ERROR_VALIDATION_VERIFICATION_CODE(1002),
    ERROR_VALIDATION_PASSWORD_ON_IMPORT(1003),
    ERROR_VALIDATION_TOO_MUCH_AMOUNT(1004),
}
