package com.ttvnp.ttj_asset_android_client.domain.model

enum class ErrorCode(val rawValue: Int) {
    NO_ERROR(0),

    // system error
    ERROR_UNKNOWN(1),
    ERROR_CANNOT_CONNECT_TO_SERVER(2),
    ERROR_LOCKED_OUT(3),

    // service error
    ERROR_UNKNOWN_SERVER_ERROR(101),
    ERROR_DEVICE_ALREADY_SETUP(102),
    ERROR_DEVICE_NOT_REGISTERED(103),
    ERROR_CANNOT_REGISTER_DEVICE(104),
    ERROR_CANNOT_UPDATE_USER(105),
    ERROR_CANNOT_UPDATE_DEVICE(106),
    ERROR_CANNOT_FIND_TARGET_USER(107),
    ERROR_CANNOT_SELF_SEND(108),
    ERROR_OLD_PASSWORD_IS_NOT_CORRECT(119),

    // validation error
    ERROR_VALIDATION_EMAIL(1001),
    ERROR_VALIDATION_VERIFICATION_CODE(1002),
    ERROR_VALIDATION_PASSWORD_ON_IMPORT(1003),
    ERROR_UPLOAD_PROFILE_IMAGE_FILE_TOO_LARGE(1004),
    ERROR_VALIDATION_TOO_MUCH_AMOUNT(1005),
    ERROR_VALIDATION_AMOUNT_LONG(1006),
}
