fastlane_version "2.64.1"
default_platform :android

platform :android do
  before_all do
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(
      api_token: ENV['CRASHLYTICS_API_KEY'],
      build_secret: ENV['CRASHLYTICS_SECRET'],
      notes_path: "release_notes.txt",
      groups: "ttj-asset-android-client",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
